service:
  name: clientsvc
# app and org for use with dashboard.serverless.com
app: ticket-back-end
org: aeriverosalguedo

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  createClient:
    description: "Create a Client"
    handler: "handlers.createClient"
    events:
      - http:
          path: "/clients"
          method: "POST"
